import com.ocs.bean.account.*;
import com.ocs.bean.event.*;

global RatingResult result;

/*
 *	动感地带3G网聊卡
 *	19元套餐
 */
rule "Rule_DG3G19_M_Z"
	activation-group "DGDD"
	salience 4
    when
    	dtEvent : DataTrafficEvent(produceLocation=="国内"&&produceChannel=="All");
    	$ruleUsage : RuleUsage(ruleID=="Rule_DG3G19_1"&&remainQuantity>=dtEvent.produceQuantity);
    then
        //System.out.println("Rule_DG3G19_M_Z");
        result.ruleName = "Rule_DG3G19_M_Z";
       	result.ruleID = $ruleUsage.ruleID;
end

rule "Rule_DG3G19_Y_SN"
	activation-group "DGDD"
	salience 5
    when
    	dtEvent : DataTrafficEvent(produceLocation=="省内"&&produceChannel=="All");
    	$ruleUsage : RuleUsage(ruleID=="Rule_DG3G19_2"&&remainQuantity>=dtEvent.produceQuantity);
    then
        //System.out.println("Rule_DG3G19_Y_SN");
        result.ruleName = "Rule_DG3G19_Y_SN";
       	result.ruleID = $ruleUsage.ruleID;
end

rule "Rule_DG3G19_Y_SNX"
	activation-group "DGDD"
	salience 6
    when
    	dtEvent : DataTrafficEvent(produceLocation=="省内"&&produceChannel=="All"&&produceTime_start>="00:00:00"&&produceTime_end<="10:00:00");
    	$ruleUsage : RuleUsage(ruleID=="Rule_DG3G19_3"&& remainQuantity>=dtEvent.produceQuantity);
    then
        //System.out.println("Rule_DG3G19_Y_SNX");
        result.ruleName = "Rule_DG3G19_Y_SNX";
        result.ruleID = $ruleUsage.ruleID;
end

rule "Rule_DG3G19_BASE"
	activation-group "DGDD"
	salience 1
    when
    	dtEvent : DataTrafficEvent(produceLocation=="国内"&&produceChannel=="All");
    	$ruleUsage : RuleUsage(ruleID=="Rule_DG3G19_4");
    then
        //System.out.println("Rule_DG3G19_BASE");
        result.ruleName = "Rule_DG3G19_BASE";
        result.ruleID = $ruleUsage.ruleID;
end

/*
 *	增值业务: 10元叠加包
 */
rule "Rule_DJ10_GN"
	activation-group "DGDD"
	salience 2
    when
    	dtEvent : DataTrafficEvent(produceLocation=="国内"&&produceChannel=="All");
    	$ruleUsage : RuleUsage(ruleID=="DJ10_1"&&remainQuantity>=dtEvent.produceQuantity);
    then
        //System.out.println("Rule_DJ10_GN");
        result.ruleName = "Rule_DJ10_GN";
        result.ruleID = $ruleUsage.ruleID;
end

rule "Rule_DJ10_SN"
	activation-group "DGDD"
	salience 1
    when
    	dtEvent : DataTrafficEvent(produceLocation=="省内"&&produceChannel=="All");
    	$ruleUsage : RuleUsage(ruleID=="DJ10_2"&&remainQuantity>=dtEvent.produceQuantity);
    then
        //System.out.println("Rule_DJ10_SN");
        result.ruleName = "Rule_DJ10_SN";
        result.ruleID = $ruleUsage.ruleID;
end

